Update unlinking a Slack app
easydigitaldownloads/edd-slack pull request #134
Opened 2021-04-19 19:29 UTC by robincornett

Fixes #131 

Proposed changes:
1. Send the oAuth token as an `Authorization` header instead of appending to the URL.
2. Use `GET` instead of `POST` for revoking.
3. Restrict revoking to administrator level users, and update the logic in that function to be a little more readable.

Setting this as a draft because I think the token is revoked even if unlinking fails, possibly, and I'm not sure unlinking is actually doing what it thinks it is. I think the token should be deleted even if the API return an error, or especially if it returns an error, but right now it only does so if the request is successful. But if the request is _not_ successful, it's not possible to really fix this from here--the store is in a loop where they can't unlink their site, but also cannot relink it.

2021-05-12 15:29 UTC, mihaijoldis commented
While testing this I was able to constantly make it brek the connection to the App. Sometimes after several link/unlin attempts and navigating to a non EDD page so that the URL query params are reset the authentication process just reloads the EDD slack settings page.

Something inside the store_oauth_token() method is causing this as the code returns early here
```
		if ( 'saving' !== $state || ! $token_type ) {
			return false;
		}
```
The `$_GET` dump right above that when it fails looks like this
```
[12-May-2021 14:51:59 UTC] Start GET: Array
(
    [post_type] => download
    [page] => edd-settings
    [tab] => extensions
    [section] => edd-slack-settings
    [code] => 2056589097684.2057878671154.9cff8cb9ed31269c840cfcdb198fea5ffd0aa3c6cdf57fafb787b9624b4e8232
    [state] => 

)
```

2021-05-12 21:58 UTC, robincornett commented
@mihaijoldis I've updated the linking behavior to add a redirect after checking in with slack so that the token is not...exposed, I guess, in the URL. Also added more checks to the token setting method. Can you check again and see if you can still break it? (Seriously I cannot.)

2021-05-12 22:43 UTC, mihaijoldis commented
@robincornett managed to break on the second attempt to reconnect.
added the debug entries I had before and again it seems to return `if ( 'saving' !== $state || ! $token_type ) {`

2021-05-12 22:50 UTC, mihaijoldis commented
Here is a small recording: https://www.loom.com/share/873c8597612743bfb8b3a938b5192de2
You can see that one the modal window closes the main settings page just reloads.

2021-05-13 11:34 UTC, robincornett commented
@mihaijoldis sorry, can you check again? I just tried it on the testing site and it linked successfully for me. I adjusted the behavior so that the user should not see the code in the URL again--once it's been recorded, the site redirects to `https://edd.thepatternmall.com/wp-admin/edit.php?post_type=download&page=edd-settings&tab=extensions&section=edd-slack-settings&edd_slack_oauth=success&edd_slack_type=updated`.

2021-05-18 09:24 UTC, mihaijoldis commented
@robincornett its deffinetly better now as I can constantly get it to connect fine. In a few tests I ran like 10-15 quick connect/disconnects it only broke once. The URL on the EDD it redirected to was

`https://edd.thepatternmall.com/wp-admin/edit.php?post_type=download&page=edd-settings&tab=extensions&section=edd-slack-settings&code=2056589097684.2088391303457.95719a88aced88a1e0aea594f2871ec9e4a4dfd0f4a18e267c5ea2acc5d23104&state`

2021-06-01 14:02 UTC, ashleyfae requested changes
This is working for me! Just requested a couple improvements, then we'll be good to go.

2021-06-01 14:02 UTC, ashleyfae commented on core/ssl-only/class-edd-slack-app-oauth-settings.php
> +				wp_safe_redirect( $redirect_uri );
```suggestion
				wp_safe_redirect( $redirect_uri );
				exit;
```

Without the exit, it actually keeps executing the rest of the code and you end up on the success page.

2021-06-01 14:02 UTC, ashleyfae commented on core/ssl-only/class-edd-slack-app-oauth-settings.php
> +			wp_safe_redirect( $redirect_uri );
```suggestion
			wp_safe_redirect( $redirect_uri );
			exit;
```

2021-06-01 14:02 UTC, ashleyfae commented on core/ssl-only/class-edd-slack-app-oauth-settings.php
> +				<a href="<?php echo $slack_uri; ?>" target="_self" class="edd-slack-app-auth button button-primary" data-token_type="main">
```suggestion
				<a href="<?php echo esc_url( $slack_uri ); ?>" target="_self" class="edd-slack-app-auth button button-primary" data-token_type="main">
```

2021-06-01 15:42 UTC, ashleyfae approved these changes

2021-06-01 15:42 UTC, merged